spring.application.name=authservice
spring.datasource.url=jdbc:h2:mem:authdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=admin
 spring.datasource.password=123456
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.output.ansi.enabled=ALWAYS
management.endpoints.web.exposure.include=health,info
user-service.url=http://localhost:8082
#jwt.secret=my_secret_key
server.port=8081
jwt.secret=my_super_secret_key_which_is_long_enough_123456
logging.level.feign=DEBUG
feign.client.config.default.loggerLevel=FULL
