spring.application.name=authservice
spring.datasource.url=jdbc:postgresql://dbauth:5432/authdb
##spring.datasource.url=jdbc:postgresql://localhost:5433/authdb
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=admin
spring.datasource.password=123456
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.output.ansi.enabled=ALWAYS
management.endpoints.web.exposure.include=health,info
user-service.url=http://user-service:8082
#user-service.url=http://localhost:8082
server.port=8081
jwt.secret=my_super_secret_key_which_is_long_enough_123456
logging.level.feign=DEBUG
feign.client.config.default.loggerLevel=FULL
feign.httpclient.enabled=false
feign.okhttp.enabled=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html


#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:authdb
#spring.datasource.driverClassName=org.h2.Driver
